import { parseProfileRole, AUTHORITATIVE_PROGRAMS } from './constants/options'

export interface ProfileCompletenessInput {
  name?: string | null
  bio?: string | null
  year?: number | null
  availability?: string | null
  department?: { name?: string | null } | null
  college?: { name?: string | null } | null
  skills?: Array<any> | null
  interests?: Array<any> | null
  projects?: Array<any> | null
  privateData?: { collegeEmail?: string | null; erp?: string | null } | null
}

export function parseProgramAndBranch(deptName?: string | null): {
  program: string | null
  branch: string | null
} {
  if (!deptName || !deptName.trim()) {
    return { program: null, branch: null }
  }
  const trimmed = deptName.trim()
  if (trimmed.includes(' - ')) {
    const parts = trimmed.split(' - ')
    return {
      program: parts[0]?.trim() || null,
      branch: parts.slice(1).join(' - ').trim() || null,
    }
  }
  const matchedProg = AUTHORITATIVE_PROGRAMS.find(
    (p) => p.name.toLowerCase() === trimmed.toLowerCase() || p.code.toLowerCase() === trimmed.toLowerCase()
  )
  if (matchedProg) {
    return { program: matchedProg.name, branch: null }
  }
  return { program: null, branch: trimmed }
}

/**
 * Evaluates the 11 REQUIRED fields for student verification requests.
 * All 11 fields must be completed before a student verification request can be submitted.
 */
export function checkVerificationReadiness(profile: ProfileCompletenessInput): {
  isReady: boolean
  completedCount: number
  totalCount: number
  percentage: number
  missingFields: string[]
  checks: Array<{
    id: string
    label: string
    completed: boolean
    value: string | null
  }>
} {
  const { role } = parseProfileRole(profile.bio || null)
  const { program, branch } = parseProgramAndBranch(profile.department?.name)
  const rawErp = profile.privateData?.erp?.trim() || null
  const isAutoGeneratedErp = rawErp ? /^erp_[0-9a-f]{8}$/i.test(rawErp) : false
  const validErp = rawErp && !isAutoGeneratedErp ? rawErp : null
  const validEmail = profile.privateData?.collegeEmail?.trim() || null

  const checks = [
    {
      id: 'name',
      label: 'Full Name',
      completed: Boolean(profile.name && profile.name.trim().length > 0),
      value: profile.name?.trim() || null,
    },
    {
      id: 'college',
      label: 'College / University',
      completed: Boolean(profile.college?.name && profile.college.name.trim().length > 0),
      value: profile.college?.name?.trim() || null,
    },
    {
      id: 'collegeEmail',
      label: 'College Email',
      completed: Boolean(validEmail && validEmail.length > 0 && validEmail.includes('@')),
      value: validEmail,
    },
    {
      id: 'erp',
      label: 'ERP ID',
      completed: Boolean(validErp && validErp.length > 0),
      value: validErp,
    },
    {
      id: 'program',
      label: 'Program / Degree',
      completed: Boolean(program && program.length > 0),
      value: program,
    },
    {
      id: 'branch',
      label: 'Branch / Specialization',
      completed: Boolean(branch && branch.length > 0),
      value: branch,
    },
    {
      id: 'year',
      label: 'Academic Year',
      completed: Boolean(profile.year && profile.year > 0),
      value: profile.year ? `Year ${profile.year}` : null,
    },
    {
      id: 'primaryRole',
      label: 'Primary Role',
      completed: Boolean(role && role.length > 0),
      value: role,
    },
    {
      id: 'skills',
      label: 'Technical Skills (1+)',
      completed: Boolean(profile.skills && profile.skills.length >= 1),
      value: profile.skills && profile.skills.length > 0 ? `${profile.skills.length} declared` : null,
    },
    {
      id: 'interests',
      label: 'Domain Interests (1+)',
      completed: Boolean(profile.interests && profile.interests.length >= 1),
      value: profile.interests && profile.interests.length > 0 ? `${profile.interests.length} declared` : null,
    },
    {
      id: 'availability',
      label: 'Availability Status',
      completed: Boolean(profile.availability && profile.availability.trim().length > 0),
      value: profile.availability?.replace(/_/g, ' ') || null,
    },
  ]

  const missingFields = checks.filter((c) => !c.completed).map((c) => c.label)
  const completedCount = checks.filter((c) => c.completed).length
  const totalCount = checks.length
  const percentage = Math.round((completedCount / totalCount) * 100)

  return {
    isReady: missingFields.length === 0,
    completedCount,
    totalCount,
    percentage,
    missingFields,
    checks,
  }
}

export function calculateProfileCompleteness(profile: ProfileCompletenessInput): {
  percentage: number
  breakdown: Array<{ label: string; completed: boolean; weight: number }>
} {
  const { role, cleanBio } = parseProfileRole(profile.bio || null)

  const items = [
    { label: 'Full Name', completed: Boolean(profile.name && profile.name.trim().length > 0), weight: 15 },
    { label: 'Primary Role', completed: Boolean(role && role.trim().length > 0), weight: 15 },
    { label: 'Bio / Intro', completed: Boolean(cleanBio && cleanBio.trim().length > 0), weight: 10 },
    { label: 'Program & Branch', completed: Boolean(profile.department?.name && profile.department.name.trim().length > 0), weight: 15 },
    { label: 'College / University', completed: Boolean(profile.college?.name && profile.college.name.trim().length > 0), weight: 10 },
    { label: 'Academic Year', completed: Boolean(profile.year && profile.year > 0), weight: 10 },
    { label: 'Technical Skills (1+)', completed: Boolean(profile.skills && profile.skills.length > 0), weight: 15 },
    { label: 'Portfolio Projects or Interests', completed: Boolean((profile.projects && profile.projects.length > 0) || (profile.interests && profile.interests.length > 0)), weight: 10 },
  ]

  const totalCompletedWeight = items.reduce((acc, item) => acc + (item.completed ? item.weight : 0), 0)

  return {
    percentage: Math.min(100, totalCompletedWeight),
    breakdown: items,
  }
}
